"""Canonical financial-research taxonomies shared by runtime and evaluations."""

from __future__ import annotations

EVENT_TYPE_CRITERIA = {
    "earnings": "Quarterly or annual results, earnings releases, or financial guidance.",
    "operations": "A material operating, commercial, supply-chain, cost, or product event.",
    "financing": "Debt, refinancing, repayment, or a general liquidity event.",
    "capital_allocation": "A dividend, buyback, equity incentive, or treasury allocation action.",
    "investment": "An external investment, securities investment, or material capital expenditure.",
    "merger_acquisition": "A merger, acquisition, divestiture, or material asset transaction.",
    "related_party": "A related-party transaction, repurchase, balance, or arrangement.",
    "guarantee": "A guarantee, counter-guarantee, or contingent-liability event.",
    "fundraising": "Use of proceeds, fundraising progress, issuance plan, or fund reallocation.",
    "accounting_policy": "Accounting policy, estimate, impairment, audit matter, or recognition issue.",
    "litigation": "A lawsuit, arbitration, judgment, asset preservation, or legal dispute.",
    "regulatory": "A regulatory action, approval, inquiry, penalty, filing, or policy change.",
    "management_change": "A change in senior management, the board, auditor, or key governance role.",
    "risk_disclosure": "A material risk disclosure that does not fit a more specific event type.",
    "other": "A financial event that does not fit the other categories.",
}

RISK_FLAG_VOCABULARY = frozenset(
    {
        "cash_flow_pressure",
        "working_capital",
        "earnings_quality",
        "nonrecurring_items",
        "margin_compression",
        "cost_inflation",
        "inventory",
        "contract_asset",
        "revenue_recognition",
        "accounting_estimate",
        "leverage",
        "liquidity",
        "refinancing",
        "guarantee",
        "contingent_liability",
        "litigation",
        "legal",
        "regulatory",
        "related_party",
        "concentration",
        "customer",
        "supplier",
        "execution",
        "execution_delay",
        "grid_connection",
        "capex",
        "market",
        "valuation",
        "dilution",
        "share_based_payment",
        "internal_control",
        "audit_quality",
        "negative_evidence",
        "disclosure_completeness",
        "accounting_policy",
        "approval_pending",
        "asset_disposal",
        "auditor_change",
        "capital_allocation",
        "compliance",
        "credit",
        "cutoff",
        "financing",
        "foreign_exchange",
        "fraud_risk",
        "fundraising",
        "going_concern",
        "governance",
        "international",
        "management_assertion",
        "pricing",
        "provision",
        "receivable",
        "research_development",
        "restricted_assets",
        "seasonality",
        "supplier_credit",
        "warranty",
    }
)
